@startuml DSS - Pagar Pedido

    actor Atendente
    participant "Sistema" as Sys
    participant "Banco de Dados" as DB

    ' Atendente registra o pedido do cliente
    Atendente -> Sys: Registra pedido(nome_cliente, telefone, endereco, bairro)
    activate Sys
    Sys -> DB: Envia os dados do pedido
    activate DB
    DB -> DB: Registra o pedido
    DB --> Sys: Retorna "Pedido Criado com Sucesso."
    deactivate DB
    Sys --> Atendente: "Pedido Criado com Sucesso."
    deactivate Sys

    ' Atendente solicita o pagamento do pedido
    Atendente -> Sys: Seleciona "Pagar Pedido"
    Sys --> Atendente: Solicita confirmação de pagamento
    Atendente -> Sys: Confirma Pagamento
    activate Sys
    Sys -> DB: Confirma Pagamento de Pedido
    activate DB
    DB -> DB: Confirma e altera status do pedido para pago
    DB --> Sys: Pagamento Confirmado
    deactivate DB
    Sys --> Atendente: "Pedido Pago com Sucesso."
    deactivate Sys

@enduml
